Profile/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [

    path('admin/', admin.site.urls),
    path('accounts/',include('UserService.urls'))

]

UserService/urls.py
from django.urls import path, include
from .views import *




urlpatterns = [

    path('',include('django.contrib.auth.urls')),
    path('', home,name='home'),
    path('signup/', signup.as_view(),name='signup'),
    path('profile/', profileView.as_view(),name='profile'),
    path('changepassword/', changepassword,name='changepassword'),
    path('address/',AddressView.as_view(),name='address'),
    path('address/<int:id>/',AddressEditView.as_view(),name='addressedit')

]

UserService/models.py
from django.contrib.auth.models import User
from django.db import models




class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    birthdate = models.DateField(null=True)


class Adress(models.Model):

    ostan_choices=(
        ('teh','تهران'),
        ('shiraz','شیراز'),
        ('esfahan','اصفهان'),
        ('tabriz','تبریز')
    )
    ostan=models.CharField(max_length=255,choices=ostan_choices,null=False)
    adress_detail=models.TextField(max_length=500,null=False,blank=False)
    pelak=models.CharField(max_length=50,null=False,blank=False)
    # TODO: need length validations
    code_posti=models.CharField(max_length=100,null=False,blank=False)
    phone_number=models.CharField(max_length=11,null=False,blank=False)
    home_phone_number=models.CharField(max_length=11,null=True,blank=True)
    user=models.ForeignKey(User,on_delete=models.CASCADE)

UserService/forms.py
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth.models import User
from django import forms
from django.views.generic import UpdateView

from UserService.models import Profile, Adress


class signUpForm(UserCreationForm):

    username=forms.CharField(max_length=255, help_text='ضروری .حداکثر 150 کاراکتر')
    first_name = forms.CharField(max_length=255, required=False, help_text='اختیاری')
    last_name = forms.CharField(max_length=255, required=False, help_text='اختیاری')
    email = forms.EmailField(max_length=255, help_text='لطفا ایمیل به فرمت مناسب استفاده شود')
    birthdate = forms.DateField(help_text='(ex: 1988-02-02)')

    class Meta:

        model=User
        fields = ('username', 'first_name', 'last_name', 'email', 'password1', 'password2','birthdate', )


# class profileForm(forms.ModelForm):
#     username=forms.CharField(disabled=True)
#     last_name = forms.CharField(max_length=255, required=False, help_text='اختیاری')
#     first_name = forms.CharField(max_length=255, required=False, help_text='اختیاری')
#     email = forms.EmailField(max_length=255)
#
#     class Meta:
#         model=User
#         fields = ['username', 'first_name', 'last_name', 'email']

class loginForm(AuthenticationForm):
    username = forms.CharField

UserService/views.py
from django.contrib.auth import authenticate, login
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.mixins import LoginRequiredMixin
from django.db import transaction
from django.http import HttpResponseRedirect
from django.views.generic import View

from .forms import *
from django.shortcuts import render, redirect

from .models import Adress


def home(request):
    return render(request,'index.html')
# def signup(request):
#     if request.method=='POST':
#         # form=UserCreationForm(request.POST)
#         form=signUpForm(request.POST)
#
#         if form.is_valid() :
#             user=form.save()
#             user.refresh_from_db()
#             user.profile.birthdate=form.cleaned_data['birthdate']
#             user.save()
#             username=form.cleaned_data['username']
#             password=form.cleaned_data['password1']
#             user=authenticate(username=username,password=password)
#             login(request=request,user=user)
#             return redirect('profile')
#
#
#     else:
#         form=signUpForm()
#     return render(request,'UserService/signup.html',{'form':form})
class signup(View):
    def post(self,request):
        form = signUpForm(request.POST)

        if form.is_valid():
            user = form.save()
            user.refresh_from_db()
            user.profile.birthdate = form.cleaned_data['birthdate']
            user.save()
            username = form.cleaned_data['username']
            password = form.cleaned_data['password1']
            user = authenticate(username=username, password=password)
            login(request=request, user=user)
            return redirect('profile')
    def get(self,request):
        form = signUpForm()
        return render(request, 'UserService/signup.html', {'form': form})



class profileView(LoginRequiredMixin,View):

    def get(self,request):
        user=request.user
        adresses=Adress.objects.all().filter(user=user)
        return render(request,'UserService/profile.html',{'adresses':adresses})

    def put(self,request):
        pass

    def post(self,request):

        for postItem in request.POST:

            if postItem=='addr_add' :
                return redirect('address')

            # elif  postItem.startswith('edit'):
            #     addressId=postItem.replace('edit_','')
            #     return redirect('addressedit')
                
            elif postItem.startswith('delete'):
                addressId=postItem.replace('delete_','')
                Adress.objects.filter(id=int(addressId)).delete()

                return redirect('profile')
            elif 'update_profile'==postItem:


                    # TODO:
                pass

        return render(request,'UserService/profile.html')

class AddressView(LoginRequiredMixin,View):

    def get(self,request):
        ostans=dict(Adress.ostan_choices)
        return render(request,'UserService/address_view.html',context={'ostans':ostans})

        
    def post(self,request):
        ostan=request.POST['ostan_select']
        address_detail=request.POST['address_detail']
        pelak=request.POST['pelak']
        code_posti=request.POST['code_posti']
        phone_number=request.POST['phone_number']
        if 'home_phone_number'  in  request.POST:
            home_phone_number= request.POST['home_phone_number']

            newaddr=Adress(ostan=ostan,adress_detail=address_detail,
                           pelak=pelak,
                           code_posti=code_posti,
                           phone_number=phone_number,
                           home_phone_number=home_phone_number,
                           user=request.user)
        else:
            newaddr=Adress(ostan=ostan,adress_detail=address_detail,
                           pelak=pelak,
                           code_posti=code_posti,
                           phone_number=phone_number,
                           user=request.user)
        newaddr.save()
        return redirect('profile') 


class AddressEditView(LoginRequiredMixin,View):

    def get(self,request,id):
        # address=Adress.objects.get(id=7)
        ostans = dict(Adress.ostan_choices)
        address=Adress.objects.get(id=id)
        return render(request,'UserService/address_update_view.html',
                      context={'address':address,'ostans':ostans})

    def post(self,request,id):
        address = Adress.objects.get(id=id)
        address.ostan = request.POST['ostan_select']
        address.adress_detail = request.POST['address_detail']
        address.pelak = request.POST['pelak']
        address.pelak = request.POST['code_posti']
        address.phone_number = request.POST['phone_number']
        if 'home_phone_number' in request.POST:
            address.home_phone_number = request.POST['home_phone_number']

        address.save()
        return redirect('profile')



@login_required
def changepassword(request):
    if request.method=='POST':
        pass

UserService/templates/UserService/address_update_view.html
{% extends '_base.html' %}
{% block content %}
        <div class=" bg-light p-4 text-right  ">
<form method="post">
                {% csrf_token %}
        <div class="row text-right">
            <label class=" col-1">استان </label>
                <select name="ostan_select" selected="selected" >
                    {% for key,value in ostans.items %}
                        <option

                                {% if address.ostan == key %} selected="selected"{% endif %} value={{ key }}>{{ value }}</option>
                    {% endfor %}
                </select>
            <div>

            </div>
        </div>
        <div class="row text-right">
            <label class=" col-1">جزییات ادرس </label>
                <input type="text" name="address_detail" required="True" value="{{ address.adress_detail }}">

            <div>

            </div>
        </div>
        <div class="row text-right">
            <label class=" col-1">پلاک  </label>
                <input type="text" name="pelak" required="True" value="{{ address.pelak }}">
            <div>

            </div>
        </div>
        <div class="row text-right">
            <label class=" col-1">کد پستی  </label>
                <input type="text" name="code_posti" required="True" value="{{ address.code_posti }}">
        </div>

        <div class="row text-right">
        <label class=" col-1">تلفن  </label>
            <input type="text" name="phone_number" required="True" value="{{ address.phone_number }}">


        </div>
        <div class="row text-right">
                <label class=" col-1">تلفن ثابت </label>
                  <input type="text" name="home_phone_number"  value="{{ address.home_phone_number }}">


        </div>

                <input type="submit" value="ثبت ">
            </form>
    </div>
{% endblock %}

UserService/templates/UserService/profile.html
{% extends '_base.html' %}

{% block content %}

<form method="post" style="direction: rtl">
    {% csrf_token %}

    <fieldset class="form-group bg-light p-4">
        <legend class="col-form-label col-sm-2 pt-0">مشخصات فردی</legend>


        <div class="row text-right">
            <label class="p-2 col-1">نام کاربری</label>

            <input disabled="True" value="{{ user.username }}"/>
        </div>
        <br>
        <div class="row text-right">
            <label class="p-2 col-1">نام </label>

            <input value="{{ user.first_name }}"/>
        </div>
        <br>
        <div class="row text-right">
            <label class="p-2 col-1">نام خانوادگی </label>

            <input value="{{ user.last_name }}"/>
        </div>
        <br>
        <div class="row text-right ">
            <label class="p-2 col-1">ایمیل </label>

            <input type="email" value="{{ user.email }}"/>
        </div>
        <br>
        <div class="row text-right ">
            <label class="p-2 col-1">تاریخ تولد </label>

            <input type="date" value="{{ user.birthdate }}" />
        </div>
        <br>

    </fieldset>

    <button type="submit" class="rounded btn-dark" name="update_profile"> update profile</button>
</form>

<form method="post" style="direction:rtl " >
    <input  type="submit" name="addr_add" value="افزودن آدرس جدید +" >

     <fieldset class="form-group bg-light p-4">
         {% if adresses %}
        <legend class="col-form-label col-sm-2 pt-0">آدرس ها</legend>
         {% endif%}

    {% csrf_token %}
    {% for addr in adresses %}


        <div class=" bg-light p-4 text-right  ">

        <div class="row text-right">
            <label class=" col-1">آدرس </label>

            <div>
                استان
        {{ addr.get_ostan_display }}
        -
        {{ addr.adress_detail }}
        -
        پلاک
        {{ addr.pelak }}
            </div>
        </div>
        <div class="row text-right">
            <label class=" col-1">کد پستی  </label>
                {{ addr.code_posti }}
            <div>

            </div>
        </div>
            <div class="row text-right">
            <label class=" col-1">تلفن  </label>
                {{ addr.phone_number }}
                {% if addr.home_phone_number %}
                    -{{ addr.home_phone_number }}
                {% endif%}
            <div>

            </div>
        </div>
    </div>

         <a class="btn" href="{%  url 'addressedit' addr.id  %}">
             <input type="button"  value="ویرایش" >

         </a>
         <input type="submit" name="delete_{{ addr.id }}" value="حذف" >

    {% endfor %}
     </fieldset>

</form>

{% endblock %}

UserService/templates/UserService/signup.html
{% extends '_base.html' %}

{% block content %}
<h2 xmlns="http://www.w3.org/1999/html">Sign up</h2>
  <form method="post">
    {% csrf_token %}
    {% for field in form %}
      <p>
        {{ field.label_tag }}<br>
        {{ field }}
        {% if field.help_text %}
          <small style="color: grey">{{ field.help_text }}</small>
        {% endif %}

        {% for error in field.errors %}
          <p style="color: red">{{ error }}</p>
        {% endfor %}
      </p>
    {% endfor %}
   {% csrf_token %}
    <button type="submit">Sign up</button>
  </form>
{% endblock %}

UserService/templates/_base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
        {% load static %}
        <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}" />
        <script src="{% static 'js/jquery-3.4.1.slim.min.js' %}"></script>
        <script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
        <script src="{% static 'js/bootstrap.min.js' %}"></script>

    <title>
        {% block title %} {% endblock %}
    </title>
</head>
<body>
<div class= "container mb-5">
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <a class="navbar-brand" href="{% url 'home' %}">Home</a>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
          <li>
            {% if user.is_authenticated %}
            <a class="nav-link" href="{% url 'profile' %}">profile</a>

          </li>
            <li>

            <a class="nav-link" href="{% url 'changepassword' %}">change password</a>

          </li>

           {% endif %}
        </ul>


          <ul class="navbar-nav ">
              {% if not user.is_authenticated %}
            <li>
                <a href = "{% url 'signup' %}"class="btn btn-outline-success my-2 my-sm-0">
            SignUp
            </a>
            </li>
            <li>
                <a href = "{% url 'login' %}"class="btn btn-outline-success my-2 my-sm-0">
            login
            </a>
            </li>
              {% else %}
              <li>

            <a class="nav-link " href="{% url 'logout' %}">logout</a>

            </li>
              {% endif %}
          </ul>



      </div>
    </nav>
    </div>
<div class="container">
{% block content %}
{% endblock %}
</div>


</body>
</html>

UserService/templates/index.html
{% extends '_base.html' %}
{% block content %}
home
{% endblock %}